analyzer:
  errors:
    use_build_context_synchronously: ignore
    depend_on_referenced_packages: ignore
    no_logic_in_create_state: ignore
    invalid_use_of_visible_for_testing_member: ignore
    unused_local_variable: ignore
    missing_required_param: warning
    missing_return: warning
    prefer_const_constructors: warning
    prefer_const_declarations: warning
    prefer_const_literals_to_create_immutables: warning 
    
include: package:flutter_lints/flutter.yaml

linter:  
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields

